Focal heuristic state interval dynoplan
quimortiz/dynoplan pull request #25
Opened 2024-04-11 11:39 UTC by akmaralAW

Sorry for the PR. 
This branch originates from status-based collision checking changes, which is used for checking motions for expansion. 

Changes of this branch are only lowLevelfocalHeuristicStateInInterval() function, which is the idea we discussed this morning. At the moment running the profile to compare the number of high-level node expansions.

2024-04-11 11:40 UTC, akmaralAW commented
for the huge PR I meant.

2024-04-11 21:07 UTC, whoenig commented on src/tdbastar/tdbastar_epsilon.cpp
> +      }
not sure how this can ever happen?

2024-04-11 21:08 UTC, whoenig commented on src/tdbastar/tdbastar_epsilon.cpp
> +        time_index_end = max_size - 1;
don't understand these two lines

2024-04-11 21:09 UTC, whoenig commented on src/tdbastar/tdbastar_epsilon.cpp
> +              tmp_traj.get_state(i); // from the motion primitive I check
your other code seems to account for potentially different dt's per robot, but here you assume that the dt's are the same?

2024-04-11 21:10 UTC, whoenig commented on src/tdbastar/tdbastar_epsilon.cpp
> +          if (violation) {
a violation occurs by definition if we have a collision. The collision checking does not use delta in our papers.

2024-04-18 05:37 UTC, whoenig requested changes
I looked at lowLevelfocalHeuristicStateInInterval and it seems reasonable.

Generally, this PR is way to big. It needs to be split up into much smaller changes, that are reviewable. One way to do this is to a) branch, b) use meld (or any other difftool) to remove everything that is unrelated to what feature you are trying to do, c) create a new PR with the relevant subset of changes. This also has the advantage that it can be tested/benchmarked independently and small PRs should reduce review turn-around times.

2024-04-18 05:37 UTC, whoenig commented on src/ompl/robots.cpp
> +    m.collision_objects_merged.push_back(std::move(co));
This is never reset, so you always just add more collision objects?

2024-04-18 05:37 UTC, whoenig commented on src/ompl/robots.cpp
> +    // create a Box with using min, max as boundaries
Did we/quim always use double for FCL rather than float? Float should be faster and accurate enough.

2024-04-18 05:37 UTC, whoenig commented on src/tdbastar/tdbastar.cpp
> +        n->arrivals[arrival_idx]; // this one naprimer, to get the parent node
"naprimer"?

2024-04-18 05:37 UTC, whoenig commented on src/tdbastar/tdbastar_epsilon.cpp
> +// single states does not assume car with trailer, ts_data ALWAYS 1
best to add an assert() in the code, rather than just a comment.

2024-04-18 08:58 UTC, closed without merging